export interface ThemePreset {
  id: string;
  name: string;
  emoji: string;
  category: "classic" | "vibrant" | "minimal" | "dark" | "nature";
  vars: Record<string, string>;
}

/** 24 portfolio color themes — applied via CSS variables */
export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "teal-light",
    name: "Teal Pro",
    emoji: "🌊",
    category: "classic",
    vars: {
      "--background": "#eef2f6",
      "--surface": "#ffffff",
      "--surface-2": "#f4f7fb",
      "--foreground": "#0c1a2a",
      "--foreground-muted": "#3d5166",
      "--muted": "#64748b",
      "--primary": "#0e7490",
      "--primary-dark": "#0f5f75",
      "--primary-light": "#0891b2",
      "--primary-glow": "rgba(14, 116, 144, 0.14)",
      "--accent": "#0d9488",
      "--card": "#ffffff",
      "--card-border": "#dce4ee",
      "--border": "#dce4ee",
      "--gradient-start": "#0e7490",
      "--gradient-mid": "#0d9488",
      "--gradient-end": "#0369a1",
    },
  },
  {
    id: "cyan-dark",
    name: "Midnight Cyan",
    emoji: "🌙",
    category: "dark",
    vars: {
      "--background": "#081018",
      "--surface": "#0f1a24",
      "--surface-2": "#152433",
      "--foreground": "#e8f1f5",
      "--foreground-muted": "#8aa3b5",
      "--muted": "#647a8b",
      "--primary": "#22d3ee",
      "--primary-dark": "#06b6d4",
      "--primary-light": "#67e8f9",
      "--primary-glow": "rgba(34, 211, 238, 0.18)",
      "--accent": "#2dd4bf",
      "--card": "#0f1a24",
      "--card-border": "#1e3344",
      "--border": "#1e3344",
      "--gradient-start": "#22d3ee",
      "--gradient-mid": "#2dd4bf",
      "--gradient-end": "#38bdf8",
    },
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    emoji: "💙",
    category: "classic",
    vars: {
      "--background": "#eef4ff",
      "--surface": "#ffffff",
      "--surface-2": "#f0f5ff",
      "--foreground": "#0f172a",
      "--foreground-muted": "#334155",
      "--muted": "#64748b",
      "--primary": "#2563eb",
      "--primary-dark": "#1d4ed8",
      "--primary-light": "#3b82f6",
      "--primary-glow": "rgba(37, 99, 235, 0.15)",
      "--accent": "#0ea5e9",
      "--card": "#ffffff",
      "--card-border": "#dbeafe",
      "--border": "#dbeafe",
      "--gradient-start": "#2563eb",
      "--gradient-mid": "#0ea5e9",
      "--gradient-end": "#6366f1",
    },
  },
  {
    id: "forest-green",
    name: "Forest Green",
    emoji: "🌲",
    category: "nature",
    vars: {
      "--background": "#ecfdf5",
      "--surface": "#ffffff",
      "--surface-2": "#f0fdf4",
      "--foreground": "#052e16",
      "--foreground-muted": "#166534",
      "--muted": "#4b5563",
      "--primary": "#059669",
      "--primary-dark": "#047857",
      "--primary-light": "#10b981",
      "--primary-glow": "rgba(5, 150, 105, 0.14)",
      "--accent": "#14b8a6",
      "--card": "#ffffff",
      "--card-border": "#bbf7d0",
      "--border": "#bbf7d0",
      "--gradient-start": "#059669",
      "--gradient-mid": "#14b8a6",
      "--gradient-end": "#0d9488",
    },
  },
  {
    id: "royal-purple",
    name: "Royal Purple",
    emoji: "💜",
    category: "vibrant",
    vars: {
      "--background": "#f5f3ff",
      "--surface": "#ffffff",
      "--surface-2": "#faf5ff",
      "--foreground": "#1e1b4b",
      "--foreground-muted": "#4c1d95",
      "--muted": "#6b7280",
      "--primary": "#7c3aed",
      "--primary-dark": "#6d28d9",
      "--primary-light": "#8b5cf6",
      "--primary-glow": "rgba(124, 58, 237, 0.15)",
      "--accent": "#a855f7",
      "--card": "#ffffff",
      "--card-border": "#ddd6fe",
      "--border": "#ddd6fe",
      "--gradient-start": "#7c3aed",
      "--gradient-mid": "#a855f7",
      "--gradient-end": "#6366f1",
    },
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    emoji: "🌅",
    category: "vibrant",
    vars: {
      "--background": "#fff7ed",
      "--surface": "#ffffff",
      "--surface-2": "#ffedd5",
      "--foreground": "#431407",
      "--foreground-muted": "#9a3412",
      "--muted": "#78716c",
      "--primary": "#ea580c",
      "--primary-dark": "#c2410c",
      "--primary-light": "#f97316",
      "--primary-glow": "rgba(234, 88, 12, 0.14)",
      "--accent": "#f59e0b",
      "--card": "#ffffff",
      "--card-border": "#fed7aa",
      "--border": "#fed7aa",
      "--gradient-start": "#ea580c",
      "--gradient-mid": "#f59e0b",
      "--gradient-end": "#ef4444",
    },
  },
  {
    id: "rose-pink",
    name: "Rose Pink",
    emoji: "🌸",
    category: "vibrant",
    vars: {
      "--background": "#fff1f2",
      "--surface": "#ffffff",
      "--surface-2": "#ffe4e6",
      "--foreground": "#4c0519",
      "--foreground-muted": "#9f1239",
      "--muted": "#6b7280",
      "--primary": "#e11d48",
      "--primary-dark": "#be123c",
      "--primary-light": "#f43f5e",
      "--primary-glow": "rgba(225, 29, 72, 0.14)",
      "--accent": "#ec4899",
      "--card": "#ffffff",
      "--card-border": "#fecdd3",
      "--border": "#fecdd3",
      "--gradient-start": "#e11d48",
      "--gradient-mid": "#ec4899",
      "--gradient-end": "#f472b6",
    },
  },
  {
    id: "slate-minimal",
    name: "Slate Minimal",
    emoji: "⬜",
    category: "minimal",
    vars: {
      "--background": "#f8fafc",
      "--surface": "#ffffff",
      "--surface-2": "#f1f5f9",
      "--foreground": "#0f172a",
      "--foreground-muted": "#475569",
      "--muted": "#64748b",
      "--primary": "#334155",
      "--primary-dark": "#1e293b",
      "--primary-light": "#475569",
      "--primary-glow": "rgba(51, 65, 85, 0.12)",
      "--accent": "#64748b",
      "--card": "#ffffff",
      "--card-border": "#e2e8f0",
      "--border": "#e2e8f0",
      "--gradient-start": "#334155",
      "--gradient-mid": "#64748b",
      "--gradient-end": "#475569",
    },
  },
  {
    id: "gold-luxury",
    name: "Gold Luxury",
    emoji: "✨",
    category: "classic",
    vars: {
      "--background": "#fffbeb",
      "--surface": "#ffffff",
      "--surface-2": "#fef3c7",
      "--foreground": "#422006",
      "--foreground-muted": "#92400e",
      "--muted": "#78716c",
      "--primary": "#b45309",
      "--primary-dark": "#92400e",
      "--primary-light": "#d97706",
      "--primary-glow": "rgba(180, 83, 9, 0.14)",
      "--accent": "#ca8a04",
      "--card": "#ffffff",
      "--card-border": "#fde68a",
      "--border": "#fde68a",
      "--gradient-start": "#b45309",
      "--gradient-mid": "#ca8a04",
      "--gradient-end": "#d97706",
    },
  },
  {
    id: "cherry-red",
    name: "Cherry Red",
    emoji: "🍒",
    category: "vibrant",
    vars: {
      "--background": "#fef2f2",
      "--surface": "#ffffff",
      "--surface-2": "#fee2e2",
      "--foreground": "#450a0a",
      "--foreground-muted": "#991b1b",
      "--muted": "#737373",
      "--primary": "#dc2626",
      "--primary-dark": "#b91c1c",
      "--primary-light": "#ef4444",
      "--primary-glow": "rgba(220, 38, 38, 0.14)",
      "--accent": "#f87171",
      "--card": "#ffffff",
      "--card-border": "#fecaca",
      "--border": "#fecaca",
      "--gradient-start": "#dc2626",
      "--gradient-mid": "#ef4444",
      "--gradient-end": "#f97316",
    },
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    emoji: "🔮",
    category: "vibrant",
    vars: {
      "--background": "#faf5ff",
      "--surface": "#ffffff",
      "--surface-2": "#f3e8ff",
      "--foreground": "#3b0764",
      "--foreground-muted": "#6b21a8",
      "--muted": "#737373",
      "--primary": "#9333ea",
      "--primary-dark": "#7e22ce",
      "--primary-light": "#a855f7",
      "--primary-glow": "rgba(147, 51, 234, 0.14)",
      "--accent": "#c084fc",
      "--card": "#ffffff",
      "--card-border": "#e9d5ff",
      "--border": "#e9d5ff",
      "--gradient-start": "#9333ea",
      "--gradient-mid": "#c084fc",
      "--gradient-end": "#818cf8",
    },
  },
  {
    id: "mint-fresh",
    name: "Mint Fresh",
    emoji: "🍃",
    category: "nature",
    vars: {
      "--background": "#f0fdfa",
      "--surface": "#ffffff",
      "--surface-2": "#ccfbf1",
      "--foreground": "#042f2e",
      "--foreground-muted": "#115e59",
      "--muted": "#64748b",
      "--primary": "#0d9488",
      "--primary-dark": "#0f766e",
      "--primary-light": "#14b8a6",
      "--primary-glow": "rgba(13, 148, 136, 0.14)",
      "--accent": "#2dd4bf",
      "--card": "#ffffff",
      "--card-border": "#99f6e4",
      "--border": "#99f6e4",
      "--gradient-start": "#0d9488",
      "--gradient-mid": "#2dd4bf",
      "--gradient-end": "#06b6d4",
    },
  },
  {
    id: "navy-corporate",
    name: "Navy Corporate",
    emoji: "🏢",
    category: "classic",
    vars: {
      "--background": "#f0f4f8",
      "--surface": "#ffffff",
      "--surface-2": "#e2e8f0",
      "--foreground": "#0a1628",
      "--foreground-muted": "#1e3a5f",
      "--muted": "#64748b",
      "--primary": "#1e40af",
      "--primary-dark": "#1e3a8a",
      "--primary-light": "#2563eb",
      "--primary-glow": "rgba(30, 64, 175, 0.14)",
      "--accent": "#0284c7",
      "--card": "#ffffff",
      "--card-border": "#cbd5e1",
      "--border": "#cbd5e1",
      "--gradient-start": "#1e40af",
      "--gradient-mid": "#0284c7",
      "--gradient-end": "#0891b2",
    },
  },
  {
    id: "emerald-night",
    name: "Emerald Night",
    emoji: "💎",
    category: "dark",
    vars: {
      "--background": "#022c22",
      "--surface": "#064e3b",
      "--surface-2": "#065f46",
      "--foreground": "#ecfdf5",
      "--foreground-muted": "#a7f3d0",
      "--muted": "#6ee7b7",
      "--primary": "#34d399",
      "--primary-dark": "#10b981",
      "--primary-light": "#6ee7b7",
      "--primary-glow": "rgba(52, 211, 153, 0.2)",
      "--accent": "#2dd4bf",
      "--card": "#064e3b",
      "--card-border": "#047857",
      "--border": "#047857",
      "--gradient-start": "#34d399",
      "--gradient-mid": "#2dd4bf",
      "--gradient-end": "#06b6d4",
    },
  },
  {
    id: "amber-warm",
    name: "Amber Warm",
    emoji: "🔥",
    category: "vibrant",
    vars: {
      "--background": "#fffbeb",
      "--surface": "#ffffff",
      "--surface-2": "#fef9c3",
      "--foreground": "#451a03",
      "--foreground-muted": "#a16207",
      "--muted": "#78716c",
      "--primary": "#d97706",
      "--primary-dark": "#b45309",
      "--primary-light": "#f59e0b",
      "--primary-glow": "rgba(217, 119, 6, 0.14)",
      "--accent": "#eab308",
      "--card": "#ffffff",
      "--card-border": "#fde68a",
      "--border": "#fde68a",
      "--gradient-start": "#d97706",
      "--gradient-mid": "#eab308",
      "--gradient-end": "#f97316",
    },
  },
  {
    id: "sky-blue",
    name: "Sky Blue",
    emoji: "☁️",
    category: "classic",
    vars: {
      "--background": "#f0f9ff",
      "--surface": "#ffffff",
      "--surface-2": "#e0f2fe",
      "--foreground": "#0c4a6e",
      "--foreground-muted": "#0369a1",
      "--muted": "#64748b",
      "--primary": "#0284c7",
      "--primary-dark": "#0369a1",
      "--primary-light": "#0ea5e9",
      "--primary-glow": "rgba(2, 132, 199, 0.14)",
      "--accent": "#38bdf8",
      "--card": "#ffffff",
      "--card-border": "#bae6fd",
      "--border": "#bae6fd",
      "--gradient-start": "#0284c7",
      "--gradient-mid": "#0ea5e9",
      "--gradient-end": "#38bdf8",
    },
  },
  {
    id: "graphite-dark",
    name: "Graphite Dark",
    emoji: "🖤",
    category: "dark",
    vars: {
      "--background": "#111827",
      "--surface": "#1f2937",
      "--surface-2": "#374151",
      "--foreground": "#f9fafb",
      "--foreground-muted": "#d1d5db",
      "--muted": "#9ca3af",
      "--primary": "#60a5fa",
      "--primary-dark": "#3b82f6",
      "--primary-light": "#93c5fd",
      "--primary-glow": "rgba(96, 165, 250, 0.18)",
      "--accent": "#818cf8",
      "--card": "#1f2937",
      "--card-border": "#374151",
      "--border": "#374151",
      "--gradient-start": "#60a5fa",
      "--gradient-mid": "#818cf8",
      "--gradient-end": "#a78bfa",
    },
  },
  {
    id: "coral-reef",
    name: "Coral Reef",
    emoji: "🪸",
    category: "vibrant",
    vars: {
      "--background": "#fff5f5",
      "--surface": "#ffffff",
      "--surface-2": "#ffe4e6",
      "--foreground": "#7f1d1d",
      "--foreground-muted": "#b91c1c",
      "--muted": "#78716c",
      "--primary": "#f97316",
      "--primary-dark": "#ea580c",
      "--primary-light": "#fb923c",
      "--primary-glow": "rgba(249, 115, 22, 0.14)",
      "--accent": "#fb7185",
      "--card": "#ffffff",
      "--card-border": "#fecdd3",
      "--border": "#fecdd3",
      "--gradient-start": "#f97316",
      "--gradient-mid": "#fb7185",
      "--gradient-end": "#f43f5e",
    },
  },
  {
    id: "indigo-deep",
    name: "Indigo Deep",
    emoji: "🌌",
    category: "dark",
    vars: {
      "--background": "#0f0a1e",
      "--surface": "#1a1033",
      "--surface-2": "#251847",
      "--foreground": "#ede9fe",
      "--foreground-muted": "#c4b5fd",
      "--muted": "#a78bfa",
      "--primary": "#818cf8",
      "--primary-dark": "#6366f1",
      "--primary-light": "#a5b4fc",
      "--primary-glow": "rgba(129, 140, 248, 0.2)",
      "--accent": "#c084fc",
      "--card": "#1a1033",
      "--card-border": "#312e81",
      "--border": "#312e81",
      "--gradient-start": "#818cf8",
      "--gradient-mid": "#c084fc",
      "--gradient-end": "#f472b6",
    },
  },
  {
    id: "wine-burgundy",
    name: "Wine Burgundy",
    emoji: "🍷",
    category: "classic",
    vars: {
      "--background": "#fdf2f8",
      "--surface": "#ffffff",
      "--surface-2": "#fce7f3",
      "--foreground": "#500724",
      "--foreground-muted": "#9d174d",
      "--muted": "#78716c",
      "--primary": "#9d174d",
      "--primary-dark": "#831843",
      "--primary-light": "#be185d",
      "--primary-glow": "rgba(157, 23, 77, 0.14)",
      "--accent": "#db2777",
      "--card": "#ffffff",
      "--card-border": "#fbcfe8",
      "--border": "#fbcfe8",
      "--gradient-start": "#9d174d",
      "--gradient-mid": "#db2777",
      "--gradient-end": "#e11d48",
    },
  },
  {
    id: "arctic-ice",
    name: "Arctic Ice",
    emoji: "❄️",
    category: "minimal",
    vars: {
      "--background": "#f8fafc",
      "--surface": "#ffffff",
      "--surface-2": "#f1f5f9",
      "--foreground": "#0f172a",
      "--foreground-muted": "#334155",
      "--muted": "#94a3b8",
      "--primary": "#0891b2",
      "--primary-dark": "#0e7490",
      "--primary-light": "#06b6d4",
      "--primary-glow": "rgba(8, 145, 178, 0.12)",
      "--accent": "#22d3ee",
      "--card": "#ffffff",
      "--card-border": "#e2e8f0",
      "--border": "#e2e8f0",
      "--gradient-start": "#0891b2",
      "--gradient-mid": "#06b6d4",
      "--gradient-end": "#22d3ee",
    },
  },
  {
    id: "neon-cyber",
    name: "Neon Cyber",
    emoji: "⚡",
    category: "dark",
    vars: {
      "--background": "#0a0a0f",
      "--surface": "#12121a",
      "--surface-2": "#1a1a26",
      "--foreground": "#f0f0ff",
      "--foreground-muted": "#a0a0c0",
      "--muted": "#707090",
      "--primary": "#00ff88",
      "--primary-dark": "#00cc6a",
      "--primary-light": "#66ffb3",
      "--primary-glow": "rgba(0, 255, 136, 0.22)",
      "--accent": "#00d4ff",
      "--card": "#12121a",
      "--card-border": "#2a2a3a",
      "--border": "#2a2a3a",
      "--gradient-start": "#00ff88",
      "--gradient-mid": "#00d4ff",
      "--gradient-end": "#a855f7",
    },
  },
  {
    id: "earth-brown",
    name: "Earth Brown",
    emoji: "🪵",
    category: "nature",
    vars: {
      "--background": "#faf6f1",
      "--surface": "#ffffff",
      "--surface-2": "#f5ebe0",
      "--foreground": "#292524",
      "--foreground-muted": "#57534e",
      "--muted": "#78716c",
      "--primary": "#92400e",
      "--primary-dark": "#78350f",
      "--primary-light": "#b45309",
      "--primary-glow": "rgba(146, 64, 14, 0.14)",
      "--accent": "#a16207",
      "--card": "#ffffff",
      "--card-border": "#e7e5e4",
      "--border": "#e7e5e4",
      "--gradient-start": "#92400e",
      "--gradient-mid": "#a16207",
      "--gradient-end": "#ca8a04",
    },
  },
  {
    id: "monochrome",
    name: "Monochrome",
    emoji: "◐",
    category: "minimal",
    vars: {
      "--background": "#ffffff",
      "--surface": "#fafafa",
      "--surface-2": "#f5f5f5",
      "--foreground": "#171717",
      "--foreground-muted": "#525252",
      "--muted": "#737373",
      "--primary": "#171717",
      "--primary-dark": "#0a0a0a",
      "--primary-light": "#404040",
      "--primary-glow": "rgba(23, 23, 23, 0.1)",
      "--accent": "#525252",
      "--card": "#fafafa",
      "--card-border": "#e5e5e5",
      "--border": "#e5e5e5",
      "--gradient-start": "#171717",
      "--gradient-mid": "#404040",
      "--gradient-end": "#737373",
    },
  },
];

export const DEFAULT_THEME_ID = "teal-light";

export function getThemeById(id: string): ThemePreset {
  return THEME_PRESETS.find((t) => t.id === id) ?? THEME_PRESETS[0];
}

export function applyThemeVars(id: string) {
  const theme = getThemeById(id);
  const root = document.documentElement;
  root.setAttribute("data-theme", id);
  for (const [key, value] of Object.entries(theme.vars)) {
    root.style.setProperty(key, value);
  }
}
